version: "3.8"
services:


  customNginx:
    volumes:
      - "/home/user/gitrepo:/gitRep"
    build: .
    image: customnginx:1.0
    ports:
      - 80:80
    environment:
      NAME: Dmytro
      AGE: 28